import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 全域 TodoProvider 包裹 App */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}

// Providers: 全域 Context
import { TodoProvider } from "@/context/TodoContext";
function Providers({ children }: { children: React.ReactNode }) {
  return <TodoProvider>{children}</TodoProvider>;
}
